language: ruby
rvm:
- 2.6.3
script:
- cp database.travis.yml config/database.yml
- rm db/seeds.rb
- cp seeds.travis.rb db/seeds.rb
- bundle exec rake db:setup
- bundle exec rspec
services:
- postgresql
